# Generated by Django 5.2.8 on 2025-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_shippingaddress_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancel', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
