# Generated by Django 5.2.8 on 2025-12-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_shippingaddress_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Giỏ hàng'), ('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('shipping', 'Đang giao'), ('completed', 'Đã giao'), ('cancel', 'Đã hủy')], default='cart', max_length=20),
        ),
    ]
