# Generated by Django 5.2.8 on 2025-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancel', 'Đã hủy')], max_length=20),
        ),
    ]
