# Generated by Django 5.2.8 on 2025-12-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_at_alter_order_status'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
    ]
