# Generated by Django 5.2.8 on 2025-12-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method_alter_order_status'),
        ('orders', '0005_merge_20251217_1345'),
    ]

    operations = [
    ]
