# Generated by Django 5.2.8 on 2025-12-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_description_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
