# Generated by Django 5.2.8 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(blank=True, help_text="Tên hiển thị cho nhóm Size (ví dụ 'Huong')", max_length=50, null=True),
        ),
    ]
