# Generated by Django 5.2.8 on 2025-12-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
