# Generated by Django 5.2.8 on 2025-12-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_productreview_is_spam_productreview_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='sentiment',
        ),
    ]
