# Generated by Django 5.2.8 on 2025-12-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_promotion'),
        ('my_app', '0010_remove_productreview_is_spam_and_more'),
    ]

    operations = [
    ]
