# Generated by Django 5.2.8 on 2025-12-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_merge_20251217_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True),
        ),
    ]
