# Generated by Django 5.2.8 on 2025-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_productreview_is_spam_productreview_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('tích cực', 'Tích cực'), ('tiêu cực', 'Tiêu cực')], max_length=10, null=True),
        ),
    ]
