# Generated by Django 5.2.8 on 2025-12-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_productreview_is_spam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('tích cực', 'Tích cực'), ('tiêu cực', 'Tiêu cực')], max_length=10, null=True),
        ),
    ]
