# Generated by Django 5.2.8 on 2026-01-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_productreview_is_spam_productreview_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng'),
        ),
    ]
