# Generated by Django 5.2.8 on 2026-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='min_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Sản phẩm phải còn hạn ít nhất X ngày để áp dụng khuyến mãi', verbose_name='Số ngày còn hạn tối thiểu'),
        ),
    ]
