# Generated by Django 5.2.8 on 2026-01-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_promotion_min_expiry_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='min_expiry_days',
        ),
    ]
