# Generated by Django 5.2.8 on 2026-01-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_promotion_min_expiry_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='import_date',
            field=models.DateField(blank=True, help_text='Ngày sản phẩm được nhập vào kho', null=True, verbose_name='Ngày nhập hàng'),
        ),
    ]
