# Generated by Django 5.2.8 on 2026-01-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_product_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_group',
            field=models.SlugField(blank=True, help_text="Các sản phẩm có cùng review_group sẽ chia sẻ chung đánh giá. VD: 'royal-canin-cho-cho'", max_length=255, null=True),
        ),
    ]
